# Tutorial on Python

This tutorial aims to provide basic introduction about Python language and numpy library.

Mostly following https://www.youtube.com/playlist?list=PLHPcpp4e3JVqYgQFM9NPo_ksEqa_bRH79.

## Markdown cells

Text can be added to Jupyter Notebooks using Markdown cells. Markdown is a lightweight markup language with plain text formatting syntax. Some cheatsheet can be found here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

## Print function

`print` function is used to display the value sent to the function

In [1]:
print(1)

1


If an expression is sent to `print`, the value will be computed and then displayed

In [2]:
print(2+2)

4


## Arithmetic operators

Some basic arithmetic operators. Note that power is done by `**`. Modular can be done by `%`.

In [3]:
print(2*3)
print(2-3)
print(2/3)
print(2.0/3)
print(2**3)
print(2%3)
print(3%2)

6
-1
0.6666666666666666
0.6666666666666666
8
2
1


You may have noticed that the result of `2/3` and `2.0/3` is different. That's because the inner data types of two expressions are different.

## Variable assignment

Use `=` to assign values to variables. You don't need to specify the data type of variables before assigning values to them.

In [4]:
x = 5

Variable name can **NOT** start with numbers

In [5]:
1x = 3

SyntaxError: invalid syntax (<ipython-input-5-d635231c729e>, line 1)

In [6]:
print(x)

5


Increment variable can be done through this: 

In [7]:
x += 1

In [8]:
print(x)

6


In [9]:
x *= 2

In [10]:
print(x)

12


Variable names can be arbitary strings

In [11]:
red = 'blue'

## String introduction

In [12]:
test_str = 'Hello world!'
test_str = "Hello world!"

In [13]:
test_str = "Hello' world!"

In [14]:
print(test_str)

Hello' world!


In [15]:
test_str + red
print(test_str + red)

Hello' world!blue


In [16]:
test_str*2

"Hello' world!Hello' world!"

In [17]:
print(test_str==red)

False


In [18]:
print(test_str==test_str)

True


In [19]:
print(test_str=='Hello world')

False


In [20]:
'Hello world!' + str(1)

'Hello world!1'

In [21]:
int(1.2)

1

In [22]:
float('1.2')

1.2

## Comments

Use `#` to comment one single line

In [23]:
# You can not see me!

Use `'''` to comment a block of codes

In [24]:
'''
print("I am invisible!")
print("We are invisible!")
'''
print(1)

1


## List

`list` is a special data type in python which can include a list of almost everything

One `list` can include multiple data types

In [25]:
my_list = ['abc', 2, 2**3, [1,'d']]

In [26]:
print(my_list)

['abc', 2, 8, [1, 'd']]


You can use index to find the value saved in the list

In [27]:
my_list[0]

'abc'

In [28]:
my_list[3]

[1, 'd']

## List slicing

Multiple ways to index values in list

In [29]:
my_list[-1]

[1, 'd']

In [30]:
my_list[-2]

8

In [31]:
my_list[1:3]

[2, 8]

In [32]:
my_list[:]

['abc', 2, 8, [1, 'd']]

In [33]:
my_list[-1]

[1, 'd']

## List method

In [34]:
len(my_list)

4

In [35]:
my_list.append(1)
print(my_list)

['abc', 2, 8, [1, 'd'], 1]


In [36]:
my_list.index(8)

2

In [37]:
my_list.remove('abc')

In [38]:
print(my_list)

[2, 8, [1, 'd'], 1]


In [39]:
test_list = [1,2,3,1]
test_list.remove(1)
print(test_list)

[2, 3, 1]


In [40]:
my_list.remove('abc')

ValueError: list.remove(x): x not in list

In [41]:
my_list.insert(0, 'abc')

In [42]:
print(my_list)

['abc', 2, 8, [1, 'd'], 1]


## Functions

In [43]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [44]:
help(my_list)

Help on list object:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /

In [45]:
dir(my_list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

## Import modules

Modules are sets of functions, data types, and classes pre-defined by other people. Through importing them, we can use things there in our script. Standard python has already come with many modules:
https://docs.python.org/2/py-modindex.html

In [46]:
import time

In [47]:
time.time()

1586201938.527081

In [48]:
curr_localtime = time.localtime(time.time())
print(curr_localtime)

time.struct_time(tm_year=2020, tm_mon=4, tm_mday=6, tm_hour=15, tm_min=38, tm_sec=59, tm_wday=0, tm_yday=97, tm_isdst=1)


In [49]:
time.asctime(curr_localtime)

'Mon Apr  6 15:38:59 2020'

## Different importing methods

In [50]:
import time as t

In [51]:
t.time()

1586201943.033762

In [52]:
from time import localtime

In [53]:
localtime(time.time())

time.struct_time(tm_year=2020, tm_mon=4, tm_mday=6, tm_hour=15, tm_min=39, tm_sec=4, tm_wday=0, tm_yday=97, tm_isdst=1)

In [54]:
from time import time

In [55]:
time

<function time.time>

In [56]:
time.asctime

AttributeError: 'builtin_function_or_method' object has no attribute 'asctime'

In [57]:
from time import *

In [58]:
asctime(localtime(time()))

'Mon Apr  6 15:39:08 2020'

In [59]:
import time

Names can get confused! Please keep the style of importing in the coding!

In [60]:
asctime

<function time.asctime>

## `for ` loops

In [61]:
for each_item in my_list:
    print(each_item)
    print(each_item=='abc')
    print
print(1)

abc
True
2
False
8
False
[1, 'd']
False
1
False
1


You can iterate over any `list`s and the iteration will always follow the order in that list

## range

In [62]:
range(10)

range(0, 10)

In [63]:
range(1, 5)

range(1, 5)

In [64]:
range(1, 7, 2)

range(1, 7, 2)

In [65]:
range(1, 7, 1.5)

TypeError: 'float' object cannot be interpreted as an integer

In [66]:
for i in range(1, 5):
    print(i**2)

1
4
9
16


In [67]:
for i in range(len(my_list)):
    print(my_list[i])

abc
2
8
[1, 'd']
1


## `while` loops

In [68]:
curr_week = 2
max_week = 10
while curr_week < max_week:
    print('At week ' + str(curr_week) + ', I am still studying!')
    curr_week += 1

print('At week ' + str(curr_week) + ', I am done with studying!')

At week 2, I am still studying!
At week 3, I am still studying!
At week 4, I am still studying!
At week 5, I am still studying!
At week 6, I am still studying!
At week 7, I am still studying!
At week 8, I am still studying!
At week 9, I am still studying!
At week 10, I am done with studying!


## Code blocks in python

You may have noticed that I have different indents for codes under the loops. 
This indention style is required by python to distinguish different code blocks

In [69]:
curr_week = 2
    max_week = 10

IndentationError: unexpected indent (<ipython-input-69-ee75ec42f332>, line 2)

## Logic in python

In [70]:
True
False

False

In [71]:
not True

False

In [72]:
False and True

False

In [73]:
False or True

True

`or` and `and` operators are shortcut operators

## `if-else` in python

In [74]:
curr_week = 2
max_week = 10

if curr_week < max_week:
    print('We still have classes')
else:
    print('We have finished all classes!')

We still have classes


In [75]:
curr_week = 2
max_week = 10

if curr_week > max_week:
    print('We have finished all classes')
elif curr_week > 1:
    print('We have finished some classes!')
elif curr_week > 2:
    print('Sth')
else:
    print('We will finish classes')

We have finished some classes!


In [76]:
a = 1
b = 2
if a>b:
    print('Win')

You can also have multiple `elif`

## Define functions

In [77]:
def my_power(x, y):
    return x**y

print(my_power(10, 2))

100


In [78]:
my_power(5, 2)

25

In [79]:
def do_sth_to_list(the_list):
    the_list.append(1)

temp_list = [1,2,3]
do_sth_to_list(temp_list)

In [80]:
temp_list

[1, 2, 3, 1]

In [81]:
import copy

temp_list = [1,2,3]
do_sth_to_list(copy.copy(temp_list))
print(temp_list)

[1, 2, 3]


In [82]:
def do_sth_to_nest_list(the_list):
    for sub_list in the_list:
        sub_list.append(1)
        
nest_list = [[1,2,3], [2,3,4]]
do_sth_to_nest_list(nest_list)
print(nest_list)

[[1, 2, 3, 1], [2, 3, 4, 1]]


In [83]:
nest_list = [[1,2,3], [2,3,4]]
do_sth_to_nest_list(copy.copy(nest_list))
print(nest_list)

[[1, 2, 3, 1], [2, 3, 4, 1]]


In [84]:
nest_list_1 = copy.copy(nest_list)

In [85]:
print(nest_list_1)

[[1, 2, 3, 1], [2, 3, 4, 1]]


In [86]:
nest_list_1.append(1)

In [87]:
print(nest_list_1)
print(nest_list)

[[1, 2, 3, 1], [2, 3, 4, 1], 1]
[[1, 2, 3, 1], [2, 3, 4, 1]]


In [88]:
nest_list = [[1,2,3], [2,3,4]]
do_sth_to_nest_list(copy.deepcopy(nest_list))
print(nest_list)

[[1, 2, 3], [2, 3, 4]]


## Dictionary in python

In [89]:
my_dict = {1: 'work', 'abc': 2, (1,2): 'Tuple'}

`Tuple` is a fixed list, no inserting or removing is allowed.

In [90]:
my_dict[2] = 3

In [91]:
my_dict

{(1, 2): 'Tuple', 1: 'work', 2: 3, 'abc': 2}

In [92]:
my_dict[2] = [3]

In [93]:
my_dict

{(1, 2): 'Tuple', 1: 'work', 2: [3], 'abc': 2}

In [94]:
my_dict

{(1, 2): 'Tuple', 1: 'work', 2: [3], 'abc': 2}

In [95]:
my_dict[1]

'work'

In [96]:
my_dict[(1,2)]

'Tuple'

In [98]:
for key in my_dict:
    print(key, my_dict[key])    

1 work
abc 2
(1, 2) Tuple
2 [3]


In [99]:
my_dict.keys()

dict_keys([1, 'abc', (1, 2), 2])

In [100]:
len(my_dict)

4

In [101]:
my_dict.items()

dict_items([(1, 'work'), ('abc', 2), ((1, 2), 'Tuple'), (2, [3])])

In [102]:
a = [1,2,3]

In [103]:
b,c,d = a

In [105]:
for key, value in my_dict.items():
    print(key, value)

1 work
abc 2
(1, 2) Tuple
2 [3]


## `class` in Python

In [106]:
class my_class:
    curr_week = 2
    max_week = 10

In [107]:
my_class

__main__.my_class

In [108]:
my_class.max_week

10

In [109]:
ins_my_class = my_class()

In [110]:
dir(ins_my_class)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'curr_week',
 'max_week']

In [111]:
ins_my_class.curr_week

2

In [112]:
ins_my_class.curr_week = 3

In [113]:
my_class.curr_week

2

### **Not a good style:**

In [114]:
my_class.curr_week = 4

In [115]:
ins_my_class_2 = my_class()

In [116]:
ins_my_class_2.curr_week

4

In [117]:
ins_my_class.curr_week

3

### Define `__init__` function in class

In [118]:
class my_class_with_init:
    curr_week = 2
    max_week = 10
    
    def __init__(self, input_week):
        self.curr_week = input_week
    
    def show_curr_week(self):
        print(self.curr_week)

In [119]:
show_curr_week()

NameError: name 'show_curr_week' is not defined

In [120]:
my_class_wi = my_class_with_init()

TypeError: __init__() missing 1 required positional argument: 'input_week'

In [121]:
my_class_wi = my_class_with_init(input_week=9)

In [122]:
my_class_wi.show_curr_week()

9


## Default values for functions

In [123]:
def func_with_default(num_rep=2, x='Hello world!'):
    print(x*num_rep)

In [124]:
func_with_default()

Hello world!Hello world!


In [125]:
func_with_default(1, 'test')

test


In [126]:
func_with_default(x='test', num_rep=2)

testtest


In [127]:
func_with_default(x='test')

testtest


# `numpy` tutorial

As Dan has mentioned, `numpy` is a module supporting tensor functions in python

In [128]:
import numpy as np

It can build some arrays

In [129]:
my_zeros = np.zeros([10,2,3,4])

In [130]:
my_zeros[1:3,0,:,:]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [131]:
my_zeros[::2,0,:,:]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [132]:
my_zeros.shape

(10, 2, 3, 4)

In [133]:
my_zeros.dtype

dtype('float64')

In [134]:
np.mean(my_zeros)

0.0

In [135]:
np.mean(my_zeros, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [136]:
np.std(my_zeros)

0.0

## Getting array from a list

In [137]:
list_for_array = [[1,2,3.0]]

In [138]:
array_from_list = np.asarray(list_for_array)
print(array_from_list)
print(array_from_list.shape)

[[1. 2. 3.]]
(1, 3)


## Generating random numbers

In [139]:
np.random.seed(0)

In [140]:
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [141]:
np.random.rand(10,2,3)

array([[[0.79172504, 0.52889492, 0.56804456],
        [0.92559664, 0.07103606, 0.0871293 ]],

       [[0.0202184 , 0.83261985, 0.77815675],
        [0.87001215, 0.97861834, 0.79915856]],

       [[0.46147936, 0.78052918, 0.11827443],
        [0.63992102, 0.14335329, 0.94466892]],

       [[0.52184832, 0.41466194, 0.26455561],
        [0.77423369, 0.45615033, 0.56843395]],

       [[0.0187898 , 0.6176355 , 0.61209572],
        [0.616934  , 0.94374808, 0.6818203 ]],

       [[0.3595079 , 0.43703195, 0.6976312 ],
        [0.06022547, 0.66676672, 0.67063787]],

       [[0.21038256, 0.1289263 , 0.31542835],
        [0.36371077, 0.57019677, 0.43860151]],

       [[0.98837384, 0.10204481, 0.20887676],
        [0.16130952, 0.65310833, 0.2532916 ]],

       [[0.46631077, 0.24442559, 0.15896958],
        [0.11037514, 0.65632959, 0.13818295]],

       [[0.19658236, 0.36872517, 0.82099323],
        [0.09710128, 0.83794491, 0.09609841]]])

In [142]:
np.random.standard_normal(10)

array([-0.02818223,  0.42833187,  0.06651722,  0.3024719 , -0.63432209,
       -0.36274117, -0.67246045, -0.35955316, -0.81314628, -1.7262826 ])