# Tutorial on Python

This tutorial aims to provide basic introduction about Python language and numpy library.

Mostly following https://www.youtube.com/playlist?list=PLHPcpp4e3JVqYgQFM9NPo_ksEqa_bRH79.

## Markdown cells

Text can be added to Jupyter Notebooks using Markdown cells. Markdown is a lightweight markup language with plain text formatting syntax. Some cheatsheet can be found here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

## Print function

`print` function is used to display the value sent to the function

In [182]:
print(1)

1


If an expression is sent to `print`, the value will be computed and then displayed

In [186]:
print(2+2)

4


## Arithmetic operators

Some basic arithmetic operators. Note that power is done by `**`. Modular can be done by `%`.

In [185]:
print(2*3)
print(2-3)
print(2/3)
print(2.0/3)
print(2**3)
print(2%3)
print(3%2)

6
-1
0
0.666666666667
8
2
1


You may have noticed that the result of `2/3` and `2.0/3` is different. That's because the inner data types of two expressions are different.

## Variable assignment

Use `=` to assign values to variables. You don't need to specify the data type of variables before assigning values to them.

In [188]:
x = 5

Variable name can **NOT** start with numbers

In [14]:
1x = 3

SyntaxError: invalid syntax (<ipython-input-14-d635231c729e>, line 1)

In [189]:
print(x)

5


Increment variable can be done through this: 

In [190]:
x += 1

In [191]:
print(x)

6


In [192]:
x *= 2

In [193]:
print(x)

12


Variable names can be arbitary strings

In [194]:
red = 'blue'

## String introduction

In [197]:
test_str = 'Hello world!'
test_str = "Hello world!"

In [199]:
test_str = "Hello' world!"

In [200]:
print(test_str)

Hello' world!


In [205]:
test_str + red
print(test_str + red)

Hello' world!blue


In [202]:
test_str*2

"Hello' world!Hello' world!"

In [203]:
print(test_str==red)

False


In [204]:
print(test_str==test_str)

True


In [26]:
print(test_str=='Hello world')

False


In [207]:
'Hello world!' + str(1)

'Hello world!1'

In [208]:
int(1.2)

1

In [209]:
float('1.2')

1.2

## Comments

Use `#` to comment one single line

In [210]:
# You can not see me!

Use `'''` to comment a block of codes

In [213]:
'''
print("I am invisible!")
print("We are invisible!")
'''
print(1)

1


## List

`list` is a special data type in python which can include a list of almost everything

One `list` can include multiple data types

In [215]:
my_list = ['abc', 2, 2**3, [1,'d']]

In [216]:
print(my_list)

['abc', 2, 8, [1, 'd']]


You can use index to find the value saved in the list

In [217]:
my_list[0]

'abc'

In [218]:
my_list[3]

[1, 'd']

## List slicing

Multiple ways to index values in list

In [219]:
my_list[-1]

[1, 'd']

In [41]:
my_list[-2]

8

In [221]:
my_list[1:3]

[2, 8]

In [222]:
my_list[:]

['abc', 2, 8, [1, 'd']]

In [223]:
my_list[-1]

[1, 'd']

## List method

In [224]:
len(my_list)

4

In [225]:
my_list.append(1)
print(my_list)

['abc', 2, 8, [1, 'd'], 1]


In [226]:
my_list.index(8)

2

In [227]:
my_list.remove('abc')

In [228]:
print(my_list)

[2, 8, [1, 'd'], 1]


In [229]:
test_list = [1,2,3,1]
test_list.remove(1)
print(test_list)

[2, 3, 1]


In [52]:
my_list.remove('abc')

ValueError: list.remove(x): x not in list

In [230]:
my_list.insert(0, 'abc')

In [231]:
print(my_list)

['abc', 2, 8, [1, 'd'], 1]


## Functions

In [56]:
help(len)

Help on built-in function len in module __builtin__:

len(...)
    len(object) -> integer
    
    Return the number of items of a sequence or collection.



In [57]:
help(my_list)

Help on list object:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(...)
 |      x.__add__(y) <==> x+y
 |  
 |  __contains__(...)
 |      x.__contains__(y) <==> y in x
 |  
 |  __delitem__(...)
 |      x.__delitem__(y) <==> del x[y]
 |  
 |  __delslice__(...)
 |      x.__delslice__(i, j) <==> del x[i:j]
 |      
 |      Use of negative indices is not supported.
 |  
 |  __eq__(...)
 |      x.__eq__(y) <==> x==y
 |  
 |  __ge__(...)
 |      x.__ge__(y) <==> x>=y
 |  
 |  __getattribute__(...)
 |      x.__getattribute__('name') <==> x.name
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __getslice__(...)
 |      x.__getslice__(i, j) <==> x[i:j]
 |      
 |      Use of negative indices is not supported.
 |  
 |  __gt__(...)
 |      x.__gt__(y) <==> x>y
 |  
 |  __iadd__(...)
 |      x.__iadd__(y) <==> x+=y
 |  
 |  __imul__(...)
 |      x.__imul__(y) <==

In [58]:
dir(my_list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setslice__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

## Import modules

Modules are sets of functions, data types, and classes pre-defined by other people. Through importing them, we can use things there in our script. Standard python has already come with many modules:
https://docs.python.org/2/py-modindex.html

In [232]:
import time

In [233]:
time.time()

1523308620.794872

In [234]:
curr_localtime = time.localtime(time.time())
print(curr_localtime)

time.struct_time(tm_year=2018, tm_mon=4, tm_mday=9, tm_hour=14, tm_min=17, tm_sec=27, tm_wday=0, tm_yday=99, tm_isdst=1)


In [235]:
time.asctime(curr_localtime)

'Mon Apr  9 14:17:27 2018'

## Different importing methods

In [66]:
import time as t

In [68]:
t.time()

1523295242.992399

In [236]:
from time import localtime

In [237]:
localtime(time.time())

time.struct_time(tm_year=2018, tm_mon=4, tm_mday=9, tm_hour=14, tm_min=22, tm_sec=2, tm_wday=0, tm_yday=99, tm_isdst=1)

In [238]:
from time import time

In [239]:
time

<function time.time>

In [240]:
time.asctime

AttributeError: 'builtin_function_or_method' object has no attribute 'asctime'

In [241]:
from time import *

In [242]:
asctime(localtime(time()))

'Mon Apr  9 14:22:57 2018'

In [243]:
import time

Names can get confused! Please keep the style of importing in the coding!

In [80]:
asctime

<function time.asctime>

## `for ` loops

In [247]:
for each_item in my_list:
    print(each_item)
    print(each_item=='abc')
    print
print(1)

abc
True

2
False

8
False

[1, 'd']
False

1
False

1


You can iterate over any `list`s and the iteration will always follow the order in that list

## range

In [84]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [85]:
range(1, 5)

[1, 2, 3, 4]

In [248]:
range(1, 7, 2)

[1, 3, 5]

In [249]:
range(1, 7, 1.5)

TypeError: range() integer step argument expected, got float.

In [250]:
for i in range(1, 5):
    print(i**2)

1
4
9
16


In [89]:
for i in range(len(my_list)):
    print(my_list[i])

abc
2
8
[1, 'd']
1


## `while` loops

In [252]:
curr_week = 2
max_week = 10
while curr_week < max_week:
    print('At week ' + str(curr_week) + ', I am still studying!')
    curr_week += 1

print('At week ' + str(curr_week) + ', I am done with studying!')

At week 2, I am still studying!
At week 3, I am still studying!
At week 4, I am still studying!
At week 5, I am still studying!
At week 6, I am still studying!
At week 7, I am still studying!
At week 8, I am still studying!
At week 9, I am still studying!
At week 10, I am done with studying!


## Code blocks in python

You may have noticed that I have different indents for codes under the loops. 
This indention style is required by python to distinguish different code blocks

In [100]:
curr_week = 2
    max_week = 10

IndentationError: unexpected indent (<ipython-input-100-ee75ec42f332>, line 2)

## Logic in python

In [254]:
True
False

False

In [255]:
not True

False

In [256]:
False and True

False

In [98]:
False or True

True

`or` and `and` operators are shortcut operators

## `if-else` in python

In [257]:
curr_week = 2
max_week = 10

if curr_week < max_week:
    print('We still have classes')
else:
    print('We have finished all classes!')

We still have classes


In [259]:
curr_week = 2
max_week = 10

if curr_week > max_week:
    print('We have finished all classes')
elif curr_week > 1:
    print('We have finished some classes!')
elif curr_week > 2:
    print('Sth')
else:
    print('We will finish classes')

We have finished some classes!


In [261]:
a = 1
b = 2
if a>b:
    print('Win')

You can also have multiple `elif`

## Define functions

In [106]:
def my_power(x, y):
    return x**y

print(my_power(10, 2))

100


In [107]:
my_power(5, 2)

25

In [263]:
def do_sth_to_list(the_list):
    the_list.append(1)

temp_list = [1,2,3]
do_sth_to_list(temp_list)

In [264]:
temp_list

[1, 2, 3, 1]

In [265]:
import copy

temp_list = [1,2,3]
do_sth_to_list(copy.copy(temp_list))
print(temp_list)

[1, 2, 3]


In [266]:
def do_sth_to_nest_list(the_list):
    for sub_list in the_list:
        sub_list.append(1)
        
nest_list = [[1,2,3], [2,3,4]]
do_sth_to_nest_list(nest_list)
print(nest_list)

[[1, 2, 3, 1], [2, 3, 4, 1]]


In [269]:
nest_list = [[1,2,3], [2,3,4]]
do_sth_to_nest_list(copy.copy(nest_list))
print(nest_list)

[[1, 2, 3, 1], [2, 3, 4, 1]]


In [274]:
nest_list_1 = copy.copy(nest_list)

In [275]:
print(nest_list_1)

[[1, 2, 3, 1], [2, 3, 4, 1], 1]


In [276]:
nest_list_1.append(1)

In [277]:
print(nest_list_1)
print(nest_list)

[[1, 2, 3, 1], [2, 3, 4, 1], 1, 1]
[[1, 2, 3, 1], [2, 3, 4, 1], 1]


In [268]:
nest_list = [[1,2,3], [2,3,4]]
do_sth_to_nest_list(copy.deepcopy(nest_list))
print(nest_list)

[[1, 2, 3], [2, 3, 4]]


## Dictionary in python

In [278]:
my_dict = {1: 'work', 'abc': 2, (1,2): 'Tuple'}

`Tuple` is a fixed list, no inserting or removing is allowed.

In [283]:
my_dict[2] = 3

In [284]:
my_dict

{1: 'work', 2: 3, 'abc': 2, (1, 2): 'Tuple'}

In [286]:
my_dict[2] = [3]

In [287]:
my_dict

{1: 'work', 2: [3], 'abc': 2, (1, 2): 'Tuple'}

In [279]:
my_dict

{1: 'work', 'abc': 2, (1, 2): 'Tuple'}

In [280]:
my_dict[1]

'work'

In [281]:
my_dict[(1,2)]

'Tuple'

In [282]:
for key in my_dict:
    print key, my_dict[key]
    print (key, my_dict[key])    
    print

(1, 2) Tuple
((1, 2), 'Tuple')

1 work
(1, 'work')

abc 2
('abc', 2)



In [288]:
my_dict.keys()

[(1, 2), 1, 2, 'abc']

In [289]:
len(my_dict)

4

In [290]:
my_dict.items()

[((1, 2), 'Tuple'), (1, 'work'), (2, [3]), ('abc', 2)]

In [291]:
a = [1,2,3]

In [292]:
b,c,d = a

In [127]:
for key, value in my_dict.items():
    print key, value

(1, 2) Tuple
1 work
abc 2


## `class` in Python

In [293]:
class my_class:
    curr_week = 2
    max_week = 10

In [294]:
my_class

<class __main__.my_class at 0x10ad65328>

In [295]:
my_class.max_week

10

In [296]:
ins_my_class = my_class()

In [135]:
dir(ins_my_class)

['__doc__', '__module__', 'curr_week', 'max_week']

In [297]:
ins_my_class.curr_week

2

In [298]:
ins_my_class.curr_week = 3

In [301]:
my_class.curr_week

2

### **Not a good style:**

In [303]:
my_class.curr_week = 4

In [304]:
ins_my_class_2 = my_class()

In [305]:
ins_my_class_2.curr_week

4

In [306]:
ins_my_class.curr_week

3

### Define `__init__` function in class

In [150]:
class my_class_with_init:
    curr_week = 2
    max_week = 10
    
    def __init__(self, input_week):
        self.curr_week = input_week
    
    def show_curr_week(self):
        print(self.curr_week)

In [308]:
show_curr_week()

NameError: name 'show_curr_week' is not defined

In [307]:
my_class_wi = my_class_with_init()

TypeError: __init__() takes exactly 2 arguments (1 given)

In [152]:
my_class_wi = my_class_with_init(input_week=9)

In [153]:
my_class_wi.show_curr_week()

9


## Default values for functions

In [156]:
def func_with_default(num_rep=2, x='Hello world!'):
    print(x*num_rep)

In [157]:
func_with_default()

Hello world!Hello world!


In [158]:
func_with_default(1, 'test')

test


In [309]:
func_with_default(x='test', num_rep=2)

testtest


In [162]:
func_with_default(x='test')

testtest


# `numpy` tutorial

As Dan has mentioned, `numpy` is a module supporting tensor functions in python

In [163]:
import numpy as np

It can build some arrays

In [314]:
my_zeros = np.zeros([10,2,3,4])

In [321]:
my_zeros[1:3,0,:,:]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [324]:
my_zeros[::2,0,:,:]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [166]:
my_zeros.shape

(10, 2)

In [167]:
my_zeros.dtype

dtype('float64')

In [168]:
np.mean(my_zeros)

0.0

In [310]:
np.mean(my_zeros, axis=0)

array([0., 0.])

In [169]:
np.std(my_zeros)

0.0

## Getting array from a list

In [312]:
list_for_array = [[1,2,3.0]]

In [313]:
array_from_list = np.asarray(list_for_array)
print(array_from_list)
print(array_from_list.shape)

[[1. 2. 3.]]
(1, 3)


## Generating random numbers

In [329]:
np.random.seed(0)

In [331]:
np.random.rand(10)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [328]:
np.random.rand(10,2,3)

array([[[0.26455561, 0.77423369, 0.45615033],
        [0.56843395, 0.0187898 , 0.6176355 ]],

       [[0.61209572, 0.616934  , 0.94374808],
        [0.6818203 , 0.3595079 , 0.43703195]],

       [[0.6976312 , 0.06022547, 0.66676672],
        [0.67063787, 0.21038256, 0.1289263 ]],

       [[0.31542835, 0.36371077, 0.57019677],
        [0.43860151, 0.98837384, 0.10204481]],

       [[0.20887676, 0.16130952, 0.65310833],
        [0.2532916 , 0.46631077, 0.24442559]],

       [[0.15896958, 0.11037514, 0.65632959],
        [0.13818295, 0.19658236, 0.36872517]],

       [[0.82099323, 0.09710128, 0.83794491],
        [0.09609841, 0.97645947, 0.4686512 ]],

       [[0.97676109, 0.60484552, 0.73926358],
        [0.03918779, 0.28280696, 0.12019656]],

       [[0.2961402 , 0.11872772, 0.31798318],
        [0.41426299, 0.0641475 , 0.69247212]],

       [[0.56660145, 0.26538949, 0.52324805],
        [0.09394051, 0.5759465 , 0.9292962 ]]])

In [176]:
np.random.standard_normal(10)

array([ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])